// This file is auto-generated by @hey-api/openapi-ts

export type Activation = {
    uid: string;
    token: string;
};

export type ActivationRequest = {
    uid: string;
    token: string;
};

export type Credit = {
    readonly id: number;
    readonly ogrn: string | null;
    readonly passport: string | null;
    readonly pledges: Array<Pledge>;
    readonly payments: Array<CreditPayment>;
    readonly payoffs: Array<CreditPayoff>;
    credit_statistics: CreditStatistics;
    ur_client_detail: UrClient | null;
    fiz_client_detail: FizClient | null;
    uuid?: string;
    term: number;
    yearlypercents: number;
    dailypennies: number;
    totalbase: number;
    readonly created_at: string;
    ur_client?: number | null;
    fiz_client?: number | null;
};

export type CreditPayment = {
    readonly id: number;
    periodStart: string;
    periodEnd: string;
    baseatstart: number;
    totalpercents: number;
    paidpercents?: number;
    unpaidpercents: number;
    totalbase: number;
    paidbase?: number;
    unpaidbase: number;
    totalpennies?: number;
    paidpennies?: number;
    unpaidpennies?: number;
    currentlypaid?: number;
    currentlyunpaid: number;
    totalpayment: number;
    updatedate?: string;
    credit: number;
};

export type CreditPaymentRequest = {
    periodStart: string;
    periodEnd: string;
    baseatstart: number;
    totalpercents: number;
    paidpercents?: number;
    unpaidpercents: number;
    totalbase: number;
    paidbase?: number;
    unpaidbase: number;
    totalpennies?: number;
    paidpennies?: number;
    unpaidpennies?: number;
    currentlypaid?: number;
    currentlyunpaid: number;
    totalpayment: number;
    updatedate?: string;
    credit: number;
};

export type CreditPayoff = {
    readonly id: number;
    penniespayment?: number;
    percentspayment?: number;
    basepaymentscheduled?: number;
    basepaymentearly?: number;
    totalPayment?: number;
    readonly payoffTime: string;
    credit: number;
};

export type CreditPayoffCreateRequest = {
    payoff_amount: number;
    credit: number;
};

export type CreditPayoffRequest = {
    penniespayment?: number;
    percentspayment?: number;
    basepaymentscheduled?: number;
    basepaymentearly?: number;
    totalPayment?: number;
    credit: number;
};

export type CreditPayoffResult = {
    credit_payoff: CreditPayoff;
    readonly remainder: number | null;
};

export type CreditRequest = {
    uuid?: string;
    term: number;
    yearlypercents: number;
    dailypennies: number;
    totalbase: number;
    ur_client?: number | null;
    fiz_client?: number | null;
};

export type CreditRestructureCreateRequest = {
    credit: number;
    term: number;
    yearlypercents: number;
    dailypennies: number;
    totalbase: number;
};

export type CreditStatistics = {
    paidpercents: number | null;
    unpaidpercents: number | null;
    paidbase: number | null;
    unpaidbase: number | null;
    paidpennies: number | null;
    unpaidpennies: number | null;
    currentlypaid: number | null;
    currentlyunpaid: number | null;
    paid_payments: number | null;
    unpaid_payments: number | null;
    timestamp: string | null;
};

export type CreditworthinessCheckRequest = {
    fiz_client: number;
    term: number;
    yearlypercents: number;
    dailypennies?: number | null;
    totalbase: number;
};

export type CreditworthinessCheckResult = {
    ok: boolean;
};

export type CurrentUser = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly username: string;
    /**
     * Email address
     */
    readonly email: string;
    /**
     * Staff status
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff: boolean;
    /**
     * Superuser status
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
};

export type FizClient = {
    readonly id: number;
    readonly is_valid_info: boolean;
    credit_statistics: CreditStatistics;
    passport: string;
    nbkiRating?: number | null;
    okbRating?: number | null;
    bkiCreditInfoRating?: number | null;
    bkiSBRating?: number | null;
    dti?: number | null;
    revolbal?: number | null;
    mthssincerecentbc?: number | null;
    bcutil?: number | null;
    revolutil?: number | null;
    annualinc: number;
    avgcurbal: number;
    totalacc: number;
    accopenpast24mths: number;
    totalbclimit: number;
    totalilhighcreditlimit: number;
    totalilrevhilim: number;
    emplength: number;
    totalbalexmort: number;
    bcopentobuy: number;
    readonly infoupdatedate: string;
};

export type FizClientRequest = {
    passport: string;
    nbkiRating?: number | null;
    okbRating?: number | null;
    bkiCreditInfoRating?: number | null;
    bkiSBRating?: number | null;
    dti?: number | null;
    revolbal?: number | null;
    mthssincerecentbc?: number | null;
    bcutil?: number | null;
    revolutil?: number | null;
    annualinc: number;
    avgcurbal: number;
    totalacc: number;
    accopenpast24mths: number;
    totalbclimit: number;
    totalilhighcreditlimit: number;
    totalilrevhilim: number;
    emplength: number;
    totalbalexmort: number;
    bcopentobuy: number;
};

export type PasswordResetConfirm = {
    uid: string;
    token: string;
    new_password: string;
};

export type PasswordResetConfirmRequest = {
    uid: string;
    token: string;
    new_password: string;
};

export type PatchedCreditPaymentRequest = {
    periodStart?: string;
    periodEnd?: string;
    baseatstart?: number;
    totalpercents?: number;
    paidpercents?: number;
    unpaidpercents?: number;
    totalbase?: number;
    paidbase?: number;
    unpaidbase?: number;
    totalpennies?: number;
    paidpennies?: number;
    unpaidpennies?: number;
    currentlypaid?: number;
    currentlyunpaid?: number;
    totalpayment?: number;
    updatedate?: string;
    credit?: number;
};

export type PatchedCreditPayoffRequest = {
    penniespayment?: number;
    percentspayment?: number;
    basepaymentscheduled?: number;
    basepaymentearly?: number;
    totalPayment?: number;
    credit?: number;
};

export type PatchedCreditRequest = {
    uuid?: string;
    term?: number;
    yearlypercents?: number;
    dailypennies?: number;
    totalbase?: number;
    ur_client?: number | null;
    fiz_client?: number | null;
};

export type PatchedFizClientRequest = {
    passport?: string;
    nbkiRating?: number | null;
    okbRating?: number | null;
    bkiCreditInfoRating?: number | null;
    bkiSBRating?: number | null;
    dti?: number | null;
    revolbal?: number | null;
    mthssincerecentbc?: number | null;
    bcutil?: number | null;
    revolutil?: number | null;
    annualinc?: number;
    avgcurbal?: number;
    totalacc?: number;
    accopenpast24mths?: number;
    totalbclimit?: number;
    totalilhighcreditlimit?: number;
    totalilrevhilim?: number;
    emplength?: number;
    totalbalexmort?: number;
    bcopentobuy?: number;
};

export type PatchedPledgeRequest = {
    vinCode?: string | null;
    cadastralNumber?: string | null;
    expectedPrice?: number;
    credit?: number;
};

export type PatchedRatingAcraRequest = {
    value?: string;
};

export type PatchedRatingExpertRequest = {
    value?: string;
};

export type PatchedRatingNcrRequest = {
    value?: string;
};

export type PatchedRatingNraRequest = {
    value?: string;
};

export type PatchedUrClientRequest = {
    ogrn?: string;
    str2300?: number;
    str1300?: number;
    str2400?: number;
    str2110pred?: number;
    str1520?: number;
    str1230?: number;
    str1510?: number;
    str2110?: number;
    str1250?: number;
    str1400?: number;
    str1500?: number;
    str1600?: number;
    str1100?: number;
    str1200?: number;
    str1550?: number;
    str1600pred?: number;
    ratingacra?: number;
    ratingnra?: number;
    ratingncr?: number;
    ratingexpert?: number;
};

export type PatchedUserRequest = {
    /**
     * Email address
     */
    email?: string;
};

export type Pledge = {
    readonly id: number;
    vinCode?: string | null;
    cadastralNumber?: string | null;
    expectedPrice: number;
    credit: number;
};

export type PledgeRequest = {
    vinCode?: string | null;
    cadastralNumber?: string | null;
    expectedPrice: number;
    credit: number;
};

export type RatingAcra = {
    readonly id: number;
    value: string;
};

export type RatingAcraRequest = {
    value: string;
};

export type RatingExpert = {
    readonly id: number;
    value: string;
};

export type RatingExpertRequest = {
    value: string;
};

export type RatingNcr = {
    readonly id: number;
    value: string;
};

export type RatingNcrRequest = {
    value: string;
};

export type RatingNra = {
    readonly id: number;
    value: string;
};

export type RatingNraRequest = {
    value: string;
};

export type SendEmailReset = {
    email: string;
};

export type SendEmailResetRequest = {
    email: string;
};

export type SetPassword = {
    new_password: string;
    current_password: string;
};

export type SetPasswordRequest = {
    new_password: string;
    current_password: string;
};

export type SetUsername = {
    current_password: string;
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    new_username: string;
};

export type SetUsernameRequest = {
    current_password: string;
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    new_username: string;
};

export type TokenCreate = {
    password?: string;
    username?: string;
};

export type TokenCreateRequest = {
    password?: string;
    username?: string;
};

export type UrClient = {
    readonly id: number;
    ratingacra_detail: RatingAcra;
    ratingnra_detail: RatingNra;
    ratingncr_detail: RatingNcr;
    ratingexpert_detail: RatingExpert;
    readonly is_valid_info: boolean;
    readonly high_risk_zayceva: boolean;
    readonly high_risk_saifullin: boolean;
    credit_statistics: CreditStatistics;
    ogrn: string;
    str2300: number;
    str1300: number;
    str2400: number;
    str2110pred: number;
    str1520: number;
    str1230: number;
    str1510: number;
    str2110: number;
    str1250: number;
    str1400: number;
    str1500: number;
    str1600: number;
    str1100: number;
    str1200: number;
    str1550: number;
    str1600pred: number;
    readonly infoupdatedate: string;
    ratingacra: number;
    ratingnra: number;
    ratingncr: number;
    ratingexpert: number;
};

export type UrClientRequest = {
    ogrn: string;
    str2300: number;
    str1300: number;
    str2400: number;
    str2110pred: number;
    str1520: number;
    str1230: number;
    str1510: number;
    str2110: number;
    str1250: number;
    str1400: number;
    str1500: number;
    str1600: number;
    str1100: number;
    str1200: number;
    str1550: number;
    str1600pred: number;
    ratingacra: number;
    ratingnra: number;
    ratingncr: number;
    ratingexpert: number;
};

export type User = {
    /**
     * Email address
     */
    email?: string;
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly username: string;
};

export type UserCreate = {
    /**
     * Email address
     */
    email?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    readonly id: number;
};

export type UserCreateRequest = {
    /**
     * Email address
     */
    email?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
};

export type UserRequest = {
    /**
     * Email address
     */
    email?: string;
};

export type UsernameResetConfirm = {
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    new_username: string;
};

export type UsernameResetConfirmRequest = {
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    new_username: string;
};

export type CreditWritable = {
    uuid?: string;
    term: number;
    yearlypercents: number;
    dailypennies: number;
    totalbase: number;
    ur_client?: number | null;
    fiz_client?: number | null;
};

export type CreditPaymentWritable = {
    periodStart: string;
    periodEnd: string;
    baseatstart: number;
    totalpercents: number;
    paidpercents?: number;
    unpaidpercents: number;
    totalbase: number;
    paidbase?: number;
    unpaidbase: number;
    totalpennies?: number;
    paidpennies?: number;
    unpaidpennies?: number;
    currentlypaid?: number;
    currentlyunpaid: number;
    totalpayment: number;
    updatedate?: string;
    credit: number;
};

export type CreditPayoffWritable = {
    penniespayment?: number;
    percentspayment?: number;
    basepaymentscheduled?: number;
    basepaymentearly?: number;
    totalPayment?: number;
    credit: number;
};

export type CreditPayoffResultWritable = {
    [key: string]: unknown;
};

export type FizClientWritable = {
    passport: string;
    nbkiRating?: number | null;
    okbRating?: number | null;
    bkiCreditInfoRating?: number | null;
    bkiSBRating?: number | null;
    dti?: number | null;
    revolbal?: number | null;
    mthssincerecentbc?: number | null;
    bcutil?: number | null;
    revolutil?: number | null;
    annualinc: number;
    avgcurbal: number;
    totalacc: number;
    accopenpast24mths: number;
    totalbclimit: number;
    totalilhighcreditlimit: number;
    totalilrevhilim: number;
    emplength: number;
    totalbalexmort: number;
    bcopentobuy: number;
};

export type PledgeWritable = {
    vinCode?: string | null;
    cadastralNumber?: string | null;
    expectedPrice: number;
    credit: number;
};

export type RatingAcraWritable = {
    value: string;
};

export type RatingExpertWritable = {
    value: string;
};

export type RatingNcrWritable = {
    value: string;
};

export type RatingNraWritable = {
    value: string;
};

export type UrClientWritable = {
    ogrn: string;
    str2300: number;
    str1300: number;
    str2400: number;
    str2110pred: number;
    str1520: number;
    str1230: number;
    str1510: number;
    str2110: number;
    str1250: number;
    str1400: number;
    str1500: number;
    str1600: number;
    str1100: number;
    str1200: number;
    str1550: number;
    str1600pred: number;
    ratingacra: number;
    ratingnra: number;
    ratingncr: number;
    ratingexpert: number;
};

export type UserWritable = {
    /**
     * Email address
     */
    email?: string;
};

export type UserCreateWritable = {
    /**
     * Email address
     */
    email?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
};

export type UserCreateRequestWritable = {
    /**
     * Email address
     */
    email?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    password: string;
};

export type AuthTokenLoginCreateData = {
    body?: TokenCreateRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token/login/';
};

export type AuthTokenLoginCreateResponses = {
    200: TokenCreate;
};

export type AuthTokenLoginCreateResponse = AuthTokenLoginCreateResponses[keyof AuthTokenLoginCreateResponses];

export type AuthTokenLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/token/logout/';
};

export type AuthTokenLogoutCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthUsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/';
};

export type AuthUsersListResponses = {
    200: Array<User>;
};

export type AuthUsersListResponse = AuthUsersListResponses[keyof AuthUsersListResponses];

export type AuthUsersCreateData = {
    body: UserCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/users/';
};

export type AuthUsersCreateResponses = {
    201: UserCreate;
};

export type AuthUsersCreateResponse = AuthUsersCreateResponses[keyof AuthUsersCreateResponses];

export type AuthUsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/auth/users/{id}/';
};

export type AuthUsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthUsersDestroyResponse = AuthUsersDestroyResponses[keyof AuthUsersDestroyResponses];

export type AuthUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/auth/users/{id}/';
};

export type AuthUsersRetrieveResponses = {
    200: User;
};

export type AuthUsersRetrieveResponse = AuthUsersRetrieveResponses[keyof AuthUsersRetrieveResponses];

export type AuthUsersPartialUpdateData = {
    body?: PatchedUserRequest;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/auth/users/{id}/';
};

export type AuthUsersPartialUpdateResponses = {
    200: User;
};

export type AuthUsersPartialUpdateResponse = AuthUsersPartialUpdateResponses[keyof AuthUsersPartialUpdateResponses];

export type AuthUsersUpdateData = {
    body?: UserRequest;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/auth/users/{id}/';
};

export type AuthUsersUpdateResponses = {
    200: User;
};

export type AuthUsersUpdateResponse = AuthUsersUpdateResponses[keyof AuthUsersUpdateResponses];

export type AuthUsersActivationCreateData = {
    body: ActivationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/activation/';
};

export type AuthUsersActivationCreateResponses = {
    200: Activation;
};

export type AuthUsersActivationCreateResponse = AuthUsersActivationCreateResponses[keyof AuthUsersActivationCreateResponses];

export type AuthUsersMeDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/me/';
};

export type AuthUsersMeDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthUsersMeDestroyResponse = AuthUsersMeDestroyResponses[keyof AuthUsersMeDestroyResponses];

export type AuthUsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/me/';
};

export type AuthUsersMeRetrieveResponses = {
    200: CurrentUser;
};

export type AuthUsersMeRetrieveResponse = AuthUsersMeRetrieveResponses[keyof AuthUsersMeRetrieveResponses];

export type AuthUsersMePartialUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/me/';
};

export type AuthUsersMePartialUpdateResponses = {
    200: CurrentUser;
};

export type AuthUsersMePartialUpdateResponse = AuthUsersMePartialUpdateResponses[keyof AuthUsersMePartialUpdateResponses];

export type AuthUsersMeUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/me/';
};

export type AuthUsersMeUpdateResponses = {
    200: CurrentUser;
};

export type AuthUsersMeUpdateResponse = AuthUsersMeUpdateResponses[keyof AuthUsersMeUpdateResponses];

export type AuthUsersResendActivationCreateData = {
    body: SendEmailResetRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/resend_activation/';
};

export type AuthUsersResendActivationCreateResponses = {
    200: SendEmailReset;
};

export type AuthUsersResendActivationCreateResponse = AuthUsersResendActivationCreateResponses[keyof AuthUsersResendActivationCreateResponses];

export type AuthUsersResetPasswordCreateData = {
    body: SendEmailResetRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/reset_password/';
};

export type AuthUsersResetPasswordCreateResponses = {
    200: SendEmailReset;
};

export type AuthUsersResetPasswordCreateResponse = AuthUsersResetPasswordCreateResponses[keyof AuthUsersResetPasswordCreateResponses];

export type AuthUsersResetPasswordConfirmCreateData = {
    body: PasswordResetConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/reset_password_confirm/';
};

export type AuthUsersResetPasswordConfirmCreateResponses = {
    200: PasswordResetConfirm;
};

export type AuthUsersResetPasswordConfirmCreateResponse = AuthUsersResetPasswordConfirmCreateResponses[keyof AuthUsersResetPasswordConfirmCreateResponses];

export type AuthUsersResetUsernameCreateData = {
    body: SendEmailResetRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/reset_username/';
};

export type AuthUsersResetUsernameCreateResponses = {
    200: SendEmailReset;
};

export type AuthUsersResetUsernameCreateResponse = AuthUsersResetUsernameCreateResponses[keyof AuthUsersResetUsernameCreateResponses];

export type AuthUsersResetUsernameConfirmCreateData = {
    body: UsernameResetConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/reset_username_confirm/';
};

export type AuthUsersResetUsernameConfirmCreateResponses = {
    200: UsernameResetConfirm;
};

export type AuthUsersResetUsernameConfirmCreateResponse = AuthUsersResetUsernameConfirmCreateResponses[keyof AuthUsersResetUsernameConfirmCreateResponses];

export type AuthUsersSetPasswordCreateData = {
    body: SetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/set_password/';
};

export type AuthUsersSetPasswordCreateResponses = {
    200: SetPassword;
};

export type AuthUsersSetPasswordCreateResponse = AuthUsersSetPasswordCreateResponses[keyof AuthUsersSetPasswordCreateResponses];

export type AuthUsersSetUsernameCreateData = {
    body: SetUsernameRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/set_username/';
};

export type AuthUsersSetUsernameCreateResponses = {
    200: SetUsername;
};

export type AuthUsersSetUsernameCreateResponse = AuthUsersSetUsernameCreateResponses[keyof AuthUsersSetUsernameCreateResponses];

export type CreditCheckFizClientCreditworthinessCreateData = {
    body: CreditworthinessCheckRequest;
    path?: never;
    query?: never;
    url: '/api/credit/check-fiz-client-creditworthiness/';
};

export type CreditCheckFizClientCreditworthinessCreateResponses = {
    200: CreditworthinessCheckResult;
};

export type CreditCheckFizClientCreditworthinessCreateResponse = CreditCheckFizClientCreditworthinessCreateResponses[keyof CreditCheckFizClientCreditworthinessCreateResponses];

export type CreditCreateCreditPayoffCreateData = {
    body: CreditPayoffCreateRequest;
    path?: never;
    query?: never;
    url: '/api/credit/create-credit-payoff/';
};

export type CreditCreateCreditPayoffCreateResponses = {
    200: CreditPayoffResult;
};

export type CreditCreateCreditPayoffCreateResponse = CreditCreateCreditPayoffCreateResponses[keyof CreditCreateCreditPayoffCreateResponses];

export type CreditCreditListData = {
    body?: never;
    path?: never;
    query?: {
        fiz_client?: number;
        fiz_client__passport?: string;
        fiz_clients_only?: boolean;
        id?: number;
        ur_client?: number;
        ur_client__ogrn?: string;
        ur_clients_only?: boolean;
        uuid?: string;
    };
    url: '/api/credit/credit/';
};

export type CreditCreditListResponses = {
    200: Array<Credit>;
};

export type CreditCreditListResponse = CreditCreditListResponses[keyof CreditCreditListResponses];

export type CreditCreditCreateData = {
    body: CreditRequest;
    path?: never;
    query?: never;
    url: '/api/credit/credit/';
};

export type CreditCreditCreateResponses = {
    201: Credit;
};

export type CreditCreditCreateResponse = CreditCreditCreateResponses[keyof CreditCreditCreateResponses];

export type CreditCreditPaymentListData = {
    body?: never;
    path?: never;
    query?: {
        credit?: number;
    };
    url: '/api/credit/credit-payment/';
};

export type CreditCreditPaymentListResponses = {
    200: Array<CreditPayment>;
};

export type CreditCreditPaymentListResponse = CreditCreditPaymentListResponses[keyof CreditCreditPaymentListResponses];

export type CreditCreditPaymentCreateData = {
    body: CreditPaymentRequest;
    path?: never;
    query?: never;
    url: '/api/credit/credit-payment/';
};

export type CreditCreditPaymentCreateResponses = {
    201: CreditPayment;
};

export type CreditCreditPaymentCreateResponse = CreditCreditPaymentCreateResponses[keyof CreditCreditPaymentCreateResponses];

export type CreditCreditPaymentDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Плановый платеж по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payment/{id}/';
};

export type CreditCreditPaymentDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditCreditPaymentDestroyResponse = CreditCreditPaymentDestroyResponses[keyof CreditCreditPaymentDestroyResponses];

export type CreditCreditPaymentRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Плановый платеж по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payment/{id}/';
};

export type CreditCreditPaymentRetrieveResponses = {
    200: CreditPayment;
};

export type CreditCreditPaymentRetrieveResponse = CreditCreditPaymentRetrieveResponses[keyof CreditCreditPaymentRetrieveResponses];

export type CreditCreditPaymentPartialUpdateData = {
    body?: PatchedCreditPaymentRequest;
    path: {
        /**
         * A unique integer value identifying this Плановый платеж по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payment/{id}/';
};

export type CreditCreditPaymentPartialUpdateResponses = {
    200: CreditPayment;
};

export type CreditCreditPaymentPartialUpdateResponse = CreditCreditPaymentPartialUpdateResponses[keyof CreditCreditPaymentPartialUpdateResponses];

export type CreditCreditPaymentUpdateData = {
    body: CreditPaymentRequest;
    path: {
        /**
         * A unique integer value identifying this Плановый платеж по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payment/{id}/';
};

export type CreditCreditPaymentUpdateResponses = {
    200: CreditPayment;
};

export type CreditCreditPaymentUpdateResponse = CreditCreditPaymentUpdateResponses[keyof CreditCreditPaymentUpdateResponses];

export type CreditCreditPayoffListData = {
    body?: never;
    path?: never;
    query?: {
        credit?: number;
    };
    url: '/api/credit/credit-payoff/';
};

export type CreditCreditPayoffListResponses = {
    200: Array<CreditPayoff>;
};

export type CreditCreditPayoffListResponse = CreditCreditPayoffListResponses[keyof CreditCreditPayoffListResponses];

export type CreditCreditPayoffCreateData = {
    body: CreditPayoffRequest;
    path?: never;
    query?: never;
    url: '/api/credit/credit-payoff/';
};

export type CreditCreditPayoffCreateResponses = {
    201: CreditPayoff;
};

export type CreditCreditPayoffCreateResponse = CreditCreditPayoffCreateResponses[keyof CreditCreditPayoffCreateResponses];

export type CreditCreditPayoffDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Выплата по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payoff/{id}/';
};

export type CreditCreditPayoffDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditCreditPayoffDestroyResponse = CreditCreditPayoffDestroyResponses[keyof CreditCreditPayoffDestroyResponses];

export type CreditCreditPayoffRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Выплата по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payoff/{id}/';
};

export type CreditCreditPayoffRetrieveResponses = {
    200: CreditPayoff;
};

export type CreditCreditPayoffRetrieveResponse = CreditCreditPayoffRetrieveResponses[keyof CreditCreditPayoffRetrieveResponses];

export type CreditCreditPayoffPartialUpdateData = {
    body?: PatchedCreditPayoffRequest;
    path: {
        /**
         * A unique integer value identifying this Выплата по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payoff/{id}/';
};

export type CreditCreditPayoffPartialUpdateResponses = {
    200: CreditPayoff;
};

export type CreditCreditPayoffPartialUpdateResponse = CreditCreditPayoffPartialUpdateResponses[keyof CreditCreditPayoffPartialUpdateResponses];

export type CreditCreditPayoffUpdateData = {
    body: CreditPayoffRequest;
    path: {
        /**
         * A unique integer value identifying this Выплата по кредиту.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit-payoff/{id}/';
};

export type CreditCreditPayoffUpdateResponses = {
    200: CreditPayoff;
};

export type CreditCreditPayoffUpdateResponse = CreditCreditPayoffUpdateResponses[keyof CreditCreditPayoffUpdateResponses];

export type CreditCreditDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Кредит.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit/{id}/';
};

export type CreditCreditDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditCreditDestroyResponse = CreditCreditDestroyResponses[keyof CreditCreditDestroyResponses];

export type CreditCreditRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Кредит.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit/{id}/';
};

export type CreditCreditRetrieveResponses = {
    200: Credit;
};

export type CreditCreditRetrieveResponse = CreditCreditRetrieveResponses[keyof CreditCreditRetrieveResponses];

export type CreditCreditPartialUpdateData = {
    body?: PatchedCreditRequest;
    path: {
        /**
         * A unique integer value identifying this Кредит.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit/{id}/';
};

export type CreditCreditPartialUpdateResponses = {
    200: Credit;
};

export type CreditCreditPartialUpdateResponse = CreditCreditPartialUpdateResponses[keyof CreditCreditPartialUpdateResponses];

export type CreditCreditUpdateData = {
    body: CreditRequest;
    path: {
        /**
         * A unique integer value identifying this Кредит.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/credit/{id}/';
};

export type CreditCreditUpdateResponses = {
    200: Credit;
};

export type CreditCreditUpdateResponse = CreditCreditUpdateResponses[keyof CreditCreditUpdateResponses];

export type CreditFizClientListData = {
    body?: never;
    path?: never;
    query?: {
        passport?: string;
    };
    url: '/api/credit/fiz-client/';
};

export type CreditFizClientListResponses = {
    200: Array<FizClient>;
};

export type CreditFizClientListResponse = CreditFizClientListResponses[keyof CreditFizClientListResponses];

export type CreditFizClientCreateData = {
    body: FizClientRequest;
    path?: never;
    query?: never;
    url: '/api/credit/fiz-client/';
};

export type CreditFizClientCreateResponses = {
    201: FizClient;
};

export type CreditFizClientCreateResponse = CreditFizClientCreateResponses[keyof CreditFizClientCreateResponses];

export type CreditFizClientDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Физическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/fiz-client/{id}/';
};

export type CreditFizClientDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditFizClientDestroyResponse = CreditFizClientDestroyResponses[keyof CreditFizClientDestroyResponses];

export type CreditFizClientRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Физическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/fiz-client/{id}/';
};

export type CreditFizClientRetrieveResponses = {
    200: FizClient;
};

export type CreditFizClientRetrieveResponse = CreditFizClientRetrieveResponses[keyof CreditFizClientRetrieveResponses];

export type CreditFizClientPartialUpdateData = {
    body?: PatchedFizClientRequest;
    path: {
        /**
         * A unique integer value identifying this Физическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/fiz-client/{id}/';
};

export type CreditFizClientPartialUpdateResponses = {
    200: FizClient;
};

export type CreditFizClientPartialUpdateResponse = CreditFizClientPartialUpdateResponses[keyof CreditFizClientPartialUpdateResponses];

export type CreditFizClientUpdateData = {
    body: FizClientRequest;
    path: {
        /**
         * A unique integer value identifying this Физическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/fiz-client/{id}/';
};

export type CreditFizClientUpdateResponses = {
    200: FizClient;
};

export type CreditFizClientUpdateResponse = CreditFizClientUpdateResponses[keyof CreditFizClientUpdateResponses];

export type CreditPledgeListData = {
    body?: never;
    path?: never;
    query?: {
        credit?: number;
    };
    url: '/api/credit/pledge/';
};

export type CreditPledgeListResponses = {
    200: Array<Pledge>;
};

export type CreditPledgeListResponse = CreditPledgeListResponses[keyof CreditPledgeListResponses];

export type CreditPledgeCreateData = {
    body: PledgeRequest;
    path?: never;
    query?: never;
    url: '/api/credit/pledge/';
};

export type CreditPledgeCreateResponses = {
    201: Pledge;
};

export type CreditPledgeCreateResponse = CreditPledgeCreateResponses[keyof CreditPledgeCreateResponses];

export type CreditPledgeDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Залог.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/pledge/{id}/';
};

export type CreditPledgeDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditPledgeDestroyResponse = CreditPledgeDestroyResponses[keyof CreditPledgeDestroyResponses];

export type CreditPledgeRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Залог.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/pledge/{id}/';
};

export type CreditPledgeRetrieveResponses = {
    200: Pledge;
};

export type CreditPledgeRetrieveResponse = CreditPledgeRetrieveResponses[keyof CreditPledgeRetrieveResponses];

export type CreditPledgePartialUpdateData = {
    body?: PatchedPledgeRequest;
    path: {
        /**
         * A unique integer value identifying this Залог.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/pledge/{id}/';
};

export type CreditPledgePartialUpdateResponses = {
    200: Pledge;
};

export type CreditPledgePartialUpdateResponse = CreditPledgePartialUpdateResponses[keyof CreditPledgePartialUpdateResponses];

export type CreditPledgeUpdateData = {
    body: PledgeRequest;
    path: {
        /**
         * A unique integer value identifying this Залог.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/pledge/{id}/';
};

export type CreditPledgeUpdateResponses = {
    200: Pledge;
};

export type CreditPledgeUpdateResponse = CreditPledgeUpdateResponses[keyof CreditPledgeUpdateResponses];

export type CreditRatingAcraListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/credit/rating-acra/';
};

export type CreditRatingAcraListResponses = {
    200: Array<RatingAcra>;
};

export type CreditRatingAcraListResponse = CreditRatingAcraListResponses[keyof CreditRatingAcraListResponses];

export type CreditRatingAcraCreateData = {
    body: RatingAcraRequest;
    path?: never;
    query?: never;
    url: '/api/credit/rating-acra/';
};

export type CreditRatingAcraCreateResponses = {
    201: RatingAcra;
};

export type CreditRatingAcraCreateResponse = CreditRatingAcraCreateResponses[keyof CreditRatingAcraCreateResponses];

export type CreditRatingAcraDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating acra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-acra/{id}/';
};

export type CreditRatingAcraDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditRatingAcraDestroyResponse = CreditRatingAcraDestroyResponses[keyof CreditRatingAcraDestroyResponses];

export type CreditRatingAcraRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating acra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-acra/{id}/';
};

export type CreditRatingAcraRetrieveResponses = {
    200: RatingAcra;
};

export type CreditRatingAcraRetrieveResponse = CreditRatingAcraRetrieveResponses[keyof CreditRatingAcraRetrieveResponses];

export type CreditRatingAcraPartialUpdateData = {
    body?: PatchedRatingAcraRequest;
    path: {
        /**
         * A unique integer value identifying this rating acra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-acra/{id}/';
};

export type CreditRatingAcraPartialUpdateResponses = {
    200: RatingAcra;
};

export type CreditRatingAcraPartialUpdateResponse = CreditRatingAcraPartialUpdateResponses[keyof CreditRatingAcraPartialUpdateResponses];

export type CreditRatingAcraUpdateData = {
    body: RatingAcraRequest;
    path: {
        /**
         * A unique integer value identifying this rating acra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-acra/{id}/';
};

export type CreditRatingAcraUpdateResponses = {
    200: RatingAcra;
};

export type CreditRatingAcraUpdateResponse = CreditRatingAcraUpdateResponses[keyof CreditRatingAcraUpdateResponses];

export type CreditRatingExpertListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/credit/rating-expert/';
};

export type CreditRatingExpertListResponses = {
    200: Array<RatingExpert>;
};

export type CreditRatingExpertListResponse = CreditRatingExpertListResponses[keyof CreditRatingExpertListResponses];

export type CreditRatingExpertCreateData = {
    body: RatingExpertRequest;
    path?: never;
    query?: never;
    url: '/api/credit/rating-expert/';
};

export type CreditRatingExpertCreateResponses = {
    201: RatingExpert;
};

export type CreditRatingExpertCreateResponse = CreditRatingExpertCreateResponses[keyof CreditRatingExpertCreateResponses];

export type CreditRatingExpertDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating expert.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-expert/{id}/';
};

export type CreditRatingExpertDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditRatingExpertDestroyResponse = CreditRatingExpertDestroyResponses[keyof CreditRatingExpertDestroyResponses];

export type CreditRatingExpertRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating expert.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-expert/{id}/';
};

export type CreditRatingExpertRetrieveResponses = {
    200: RatingExpert;
};

export type CreditRatingExpertRetrieveResponse = CreditRatingExpertRetrieveResponses[keyof CreditRatingExpertRetrieveResponses];

export type CreditRatingExpertPartialUpdateData = {
    body?: PatchedRatingExpertRequest;
    path: {
        /**
         * A unique integer value identifying this rating expert.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-expert/{id}/';
};

export type CreditRatingExpertPartialUpdateResponses = {
    200: RatingExpert;
};

export type CreditRatingExpertPartialUpdateResponse = CreditRatingExpertPartialUpdateResponses[keyof CreditRatingExpertPartialUpdateResponses];

export type CreditRatingExpertUpdateData = {
    body: RatingExpertRequest;
    path: {
        /**
         * A unique integer value identifying this rating expert.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-expert/{id}/';
};

export type CreditRatingExpertUpdateResponses = {
    200: RatingExpert;
};

export type CreditRatingExpertUpdateResponse = CreditRatingExpertUpdateResponses[keyof CreditRatingExpertUpdateResponses];

export type CreditRatingNcrListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/credit/rating-ncr/';
};

export type CreditRatingNcrListResponses = {
    200: Array<RatingNcr>;
};

export type CreditRatingNcrListResponse = CreditRatingNcrListResponses[keyof CreditRatingNcrListResponses];

export type CreditRatingNcrCreateData = {
    body: RatingNcrRequest;
    path?: never;
    query?: never;
    url: '/api/credit/rating-ncr/';
};

export type CreditRatingNcrCreateResponses = {
    201: RatingNcr;
};

export type CreditRatingNcrCreateResponse = CreditRatingNcrCreateResponses[keyof CreditRatingNcrCreateResponses];

export type CreditRatingNcrDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating ncr.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-ncr/{id}/';
};

export type CreditRatingNcrDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditRatingNcrDestroyResponse = CreditRatingNcrDestroyResponses[keyof CreditRatingNcrDestroyResponses];

export type CreditRatingNcrRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating ncr.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-ncr/{id}/';
};

export type CreditRatingNcrRetrieveResponses = {
    200: RatingNcr;
};

export type CreditRatingNcrRetrieveResponse = CreditRatingNcrRetrieveResponses[keyof CreditRatingNcrRetrieveResponses];

export type CreditRatingNcrPartialUpdateData = {
    body?: PatchedRatingNcrRequest;
    path: {
        /**
         * A unique integer value identifying this rating ncr.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-ncr/{id}/';
};

export type CreditRatingNcrPartialUpdateResponses = {
    200: RatingNcr;
};

export type CreditRatingNcrPartialUpdateResponse = CreditRatingNcrPartialUpdateResponses[keyof CreditRatingNcrPartialUpdateResponses];

export type CreditRatingNcrUpdateData = {
    body: RatingNcrRequest;
    path: {
        /**
         * A unique integer value identifying this rating ncr.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-ncr/{id}/';
};

export type CreditRatingNcrUpdateResponses = {
    200: RatingNcr;
};

export type CreditRatingNcrUpdateResponse = CreditRatingNcrUpdateResponses[keyof CreditRatingNcrUpdateResponses];

export type CreditRatingNraListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/credit/rating-nra/';
};

export type CreditRatingNraListResponses = {
    200: Array<RatingNra>;
};

export type CreditRatingNraListResponse = CreditRatingNraListResponses[keyof CreditRatingNraListResponses];

export type CreditRatingNraCreateData = {
    body: RatingNraRequest;
    path?: never;
    query?: never;
    url: '/api/credit/rating-nra/';
};

export type CreditRatingNraCreateResponses = {
    201: RatingNra;
};

export type CreditRatingNraCreateResponse = CreditRatingNraCreateResponses[keyof CreditRatingNraCreateResponses];

export type CreditRatingNraDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating nra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-nra/{id}/';
};

export type CreditRatingNraDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditRatingNraDestroyResponse = CreditRatingNraDestroyResponses[keyof CreditRatingNraDestroyResponses];

export type CreditRatingNraRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating nra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-nra/{id}/';
};

export type CreditRatingNraRetrieveResponses = {
    200: RatingNra;
};

export type CreditRatingNraRetrieveResponse = CreditRatingNraRetrieveResponses[keyof CreditRatingNraRetrieveResponses];

export type CreditRatingNraPartialUpdateData = {
    body?: PatchedRatingNraRequest;
    path: {
        /**
         * A unique integer value identifying this rating nra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-nra/{id}/';
};

export type CreditRatingNraPartialUpdateResponses = {
    200: RatingNra;
};

export type CreditRatingNraPartialUpdateResponse = CreditRatingNraPartialUpdateResponses[keyof CreditRatingNraPartialUpdateResponses];

export type CreditRatingNraUpdateData = {
    body: RatingNraRequest;
    path: {
        /**
         * A unique integer value identifying this rating nra.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/rating-nra/{id}/';
};

export type CreditRatingNraUpdateResponses = {
    200: RatingNra;
};

export type CreditRatingNraUpdateResponse = CreditRatingNraUpdateResponses[keyof CreditRatingNraUpdateResponses];

export type CreditRestructureCreditCreateData = {
    body: CreditRestructureCreateRequest;
    path?: never;
    query?: never;
    url: '/api/credit/restructure-credit/';
};

export type CreditRestructureCreditCreateResponses = {
    200: Credit;
};

export type CreditRestructureCreditCreateResponse = CreditRestructureCreditCreateResponses[keyof CreditRestructureCreditCreateResponses];

export type CreditUrClientListData = {
    body?: never;
    path?: never;
    query?: {
        ogrn?: string;
    };
    url: '/api/credit/ur-client/';
};

export type CreditUrClientListResponses = {
    200: Array<UrClient>;
};

export type CreditUrClientListResponse = CreditUrClientListResponses[keyof CreditUrClientListResponses];

export type CreditUrClientCreateData = {
    body: UrClientRequest;
    path?: never;
    query?: never;
    url: '/api/credit/ur-client/';
};

export type CreditUrClientCreateResponses = {
    201: UrClient;
};

export type CreditUrClientCreateResponse = CreditUrClientCreateResponses[keyof CreditUrClientCreateResponses];

export type CreditUrClientDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Юридическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/ur-client/{id}/';
};

export type CreditUrClientDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CreditUrClientDestroyResponse = CreditUrClientDestroyResponses[keyof CreditUrClientDestroyResponses];

export type CreditUrClientRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Юридическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/ur-client/{id}/';
};

export type CreditUrClientRetrieveResponses = {
    200: UrClient;
};

export type CreditUrClientRetrieveResponse = CreditUrClientRetrieveResponses[keyof CreditUrClientRetrieveResponses];

export type CreditUrClientPartialUpdateData = {
    body?: PatchedUrClientRequest;
    path: {
        /**
         * A unique integer value identifying this Юридическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/ur-client/{id}/';
};

export type CreditUrClientPartialUpdateResponses = {
    200: UrClient;
};

export type CreditUrClientPartialUpdateResponse = CreditUrClientPartialUpdateResponses[keyof CreditUrClientPartialUpdateResponses];

export type CreditUrClientUpdateData = {
    body: UrClientRequest;
    path: {
        /**
         * A unique integer value identifying this Юридическое лицо.
         */
        id: number;
    };
    query?: never;
    url: '/api/credit/ur-client/{id}/';
};

export type CreditUrClientUpdateResponses = {
    200: UrClient;
};

export type CreditUrClientUpdateResponse = CreditUrClientUpdateResponses[keyof CreditUrClientUpdateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};
